CREATE TABLE LEMAI_COMPANY
(
		Company VARCHAR(50) NOT NULL,
		Phone CHAR(12) NOT NULL,
		Address VARCHAR(100) NOT NULL,
		City VARCHAR(25) NOT NULL,
		State VARCHAR(2) NOT NULL,
		ZIP CHAR(6) NOT NULL,
		DepartmentID INT,
	CONSTRAINT COMP_FK FOREIGN KEY(DepartmentID)
			REFERENCES LEMAI_DEPARTMENT(DepartmentID)
);

CREATE TABLE LEMAI_EMPLOYEE
(
		EmployeeID INT NOT NULL AUTO_INCREMENT,
		DepartmentID INT NOT NULL,
		JobID INT NOT NULL,
		FirstName VARCHAR(25),
		LastName VARCHAR(25),
		Salary NUMERIC(8,2),
		SocialSecurity VARCHAR(12),
		Phone CHAR(12) NOT NULL,
		Address VARCHAR(100) NOT NULL,
		City VARCHAR(25) NOT NULL,
		State VARCHAR(2) NOT NULL,
		ZIP CHAR(6) NOT NULL,
		CONSTRAINT EMPLOYEE_PK PRIMARY KEY(EmployeeID),
		CONSTRAINT EMPLOYEE_FK FOREIGN KEY(DepartmentID)
			REFERENCES LEMAI_DEPARTMENT(DepartmentID)
			ON UPDATE CASCADE
);

CREATE TABLE LEMAI_JOB
(
		JobID INT NOT NULL AUTO_INCREMENT,
		Title VARCHAR(25),
		CONSTRAINT JOB_PK PRIMARY KEY(JobID)
);

CREATE TABLE LEMAI_DEPARTMENT
(
		DepartmentID INT NOT NULL AUTO_INCREMENT,
		DepartmentName	VARCHAR(35),
		CONSTRAINT		DEPARTMENT_PK 	PRIMARY KEY(DepartmentID)
		);

CREATE TABLE LEMAI_CUSTOMER
(
		CustomerID INT NOT NULL AUTO_INCREMENT,
		CustomerRepID INT,
		FirstName VARCHAR(25),
		LastName VARCHAR(25),
		Organization VARCHAR(25),
		Email VARCHAR(100) NOT NULL,
		Phone CHAR(12) NOT NULL,
		CONSTRAINT CUSTOMER_PK PRIMARY KEY(CustomerID),
		CONSTRAINT CUSTOMER_FK FOREIGN KEY(CustomerRepID)
			REFERENCES LEMAI_EMPLOYEE(EmployeeID)
			ON UPDATE CASCADE
);
CREATE TABLE LEMAI_EQUIPMENT
(
		EquipmentID INT NOT NULL AUTO_INCREMENT,
		Equipment VARCHAR(25),
		Quantity CHAR(10) NOT NULL DEFAULT 1,
		CONSTRAINT EQUIPMENT_PK PRIMARY KEY(EquipmentID)
);
CREATE TABLE LEMAI_PROJECT
(
		ProjectID INT NOT NULL AUTO_INCREMENT,
		CustomerID INT,
		EquipmentID INT,
		Name VARCHAR(25),
		ProjectType VARCHAR(25) NOT NULL,
		ProjectStatus VARCHAR(25) NOT NULL,
		Cost NUMERIC (8,2),
		ContractPrice NUMERIC (8,2),
		CONSTRAINT PROJECT_PK PRIMARY KEY(ProjectID),
		CONSTRAINT PROJECT_FK_1 FOREIGN KEY(CustomerID)
			REFERENCES LEMAI_CUSTOMER(CustomerID),
		CONSTRAINT PROJECT_FK_2 FOREIGN KEY(EquipmentID)
			REFERENCES LEMAI_EQUIPMENT(EquipmentID),
		CONSTRAINT PROJECT_CHK_1 CHECK(ProjectType IN ('Campaign','Show','Fitting')),
		CONSTRAINT PROJECT_CHK_2 CHECK(ProjectStatus IN ('Preparing','In Progress','Reviewing','Completed'))
);

CREATE TABLE LEMAI_PROJECT_EMPLOYEE
(
		EmployeeID INT,
		ProjectID INT,
		CONSTRAINT PROEMP_PK_1 PRIMARY KEY(EmployeeID,ProjectID),
		CONSTRAINT PROEMP_FK_1 FOREIGN KEY(EmployeeID)
			REFERENCES LEMAI_EMPLOYEE(EmployeeID),
		CONSTRAINT PROEMP_FK_2 FOREIGN KEY(ProjectID)
		 REFERENCES LEMAI_PROJECT(ProjectID)
);